### ISSUE TITLE
Override Permission

### ISSUE THREAD

**Issue by F3hliks** [RockinChaos/FakeCreative#8]
### Describe The Feature

Admins are not able to go into regular creative mode (for example to use Axiom)

### Expected Solution

It would be nice if you could set up permissions in a way that you can grant admins the ability to keep using the real creative mode and have normal players go into the fake creative mode

### Describe Alternatives Considered

Add a permission and a setting in the config to enable / disable this feature

### Additional Context

I have a spot on my server where players can freely decorate their own room and want to use the fake creative mode plugin for this, as you get a seperate inventory and can't clone items.

### Checklist

- [x] I have read the wiki to make sure my request has not already been implemented.
- [ ] I ticked all of these boxes without actually reading them.
- [x] I have checked that my feature request is unique and another request does not exist.

**Comment by RockinChaos** [comment]
> nice, thank you, I'd be happy to test this!

Now available for testing in the latest snapshot.
If you are upgrading from a previous snapshot you will need to manually add the following to your config.yml;
```
# These are gamemode command aliases that will be registered on server startup (requires restart to take effect).
Commands:
  Enabled: true
  Aliases:
    - 'gamemode'
    - 'gm'
```

Otherwise if you are upgrading from a release version there is no need to do anything, you can configure the aliases by modifying the default ones listed in the config.yml.

In my testing this seems to work as intended without breaking things for those who do not want to mess with aliases.

Let me know if you encounter any issues!

EDIT: Now available in the latest release.
